[tool.poetry]
name = "Personal_assistant_bot"
version = "0.1.0"
description = ""
authors = ["Kollos777 <kolloslit@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
